os:
- linux
- osx

dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libreadline6-dev
language: cpp
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

install:
- if test -e scripts/travis/$TRAVIS_OS_NAME/$CC/install; then scripts/travis/$TRAVIS_OS_NAME/$CC/install; fi

script:
- autoreconf -is
- scripts/travis/$TRAVIS_OS_NAME/$CC/configure
- make
- VERBOSE=true make check
