dist: trusty
sudo: required
language: cpp
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libreadline6-dev

script:
- autoreconf -is
- ./configure
- make
- VERBOSE=true make check
