.TH with-readline 1
.SH NAME
with-readline \- readline frontend for arbitrary programs
.SH SYNOPSIS
.B with-readline
.RI [OPTIONS]
.B --
.I COMMAND
.IR ARGS ...
.SH DESCRIPTION
.B with-readline
executes
.B COMMAND
with Readline applied to its standard input.  This allows Readline's
editing features to be applied even to programs not linked against it.
.\" arch-tag:TbM3GaF2DXtSQBNh0cKifQ
